//MICROSERVIÇO QUE TOMA CONTA DE ROTAS E VIEWS
const express = require('express');
//EXECUTA O EXPRESS
const app = express();
//ROTA RAIS http://localhost:3001/
app.get('/', (req, res) => {
    //QUANDO ACESSAMOS LINK DO SITE DAMOS F5 ESTAMOS ACESSANDO O SERVIDOR E O REQ TEM TODOS DETALHES DESTA REQUIZIÇÃO (PARAMETROS USUÁRIO AUTENTICAÇÃO BODY IP)
    //RES É PARA RETORNAR OS DADOS
    res.send('Olá Teste');
});
//FALO PARA A APLICAÇÃO OUVIR A PORTA 3001
app.listen(3001);